### ISSUE TITLE
exclude array value

### ISSUE THREAD

**Issue by arryanggaputra** [tiaanduplessis/react-hook-form-persist#20]
Thank you for this useful lib, anw, I tried to passing exclude parameter for array field, so I have array field 

```js 
setValue(`attributes[${index}].value`, theDate);
```

but this value not excluding from storage, do you have some suggestions?

**Comment by tiaanduplessis** [comment]
Hi @arryanggaputra. The issue should be resolved in [v3.0.0](https://github.com/tiaanduplessis/react-hook-form-persist/releases/tag/v3.0.0)
