### ISSUE TITLE
Add something like include as well as ignore to persist certain form data

### ISSUE THREAD

**Issue by nelsyeung** [tiaanduplessis/react-hook-form-persist#5]
Is it possible to add something like `include` as well as `ignore` to persist certain form data?

## Reason
- Currently, the storage will still store the form data being ignored, as this package performs ignore after loading the data. This means that you can't prevent it from storing sensitive data, like a password field.
- There is also a small performance and storage overhead watching unnecessary fields, albeit a negligible one.

## Proposal
Supply `include` into `watch` (I've renamed `ignore` to `exclude` to align with the change):
```javascript
export default (
  name,
  watch,
  setValue,
  { include, exclude, storage = window.sessionStorage } = {}
) => {
  const values = watch(include);

  useEffect(() => {
    const storageItem = storage.getItem(name);

    if (storageItem) {
      Object.entries(JSON.parse(storageItem)).forEach(([key, value]) => {
        if (!exclude?.includes(key)) {
          setValue(key, value);
        }
      });
    }
  }, [name]);

  useEffect(() => storage.setItem(name, JSON.stringify(values)));

  return { clear: () => storage.removeItem(name) };
};
```

### Example usage:
```javascript
// Persist all form fields
useFormPersist('form', watch, setValue);

// Persist all form fields except password
useFormPersist('form', watch, setValue, { exclude: ['password'] });

// Persist only the email field
useFormPersist('form', watch, setValue, { include: ['email'] });
```

**Comment by tiaanduplessis** [comment]
@nelsyeung thanks for opening up the issue. I agree that it will be valuable. Should hopefully have time later this week to implement the change.

**Comment by nelsyeung** [comment]
@tiaanduplessis Wow, that was quick. Using the new version now, it seems perfect. Thanks!!!
